version: '2'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/POSTGRES
      - SPRING_DATASOURCE_USERNAME=POSTGRES
      - SPRING_DATASOURCE_PASSWORD=POSTGRES
      - MINIO_URL=http://minio:9000
      - MINIO_PUBLIC_URL=http://localhost:9000
      - MINIO_LOGIN=minioadmin
      - MINIO_PASSWORD=minioadmin
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=POSTGRES
      - POSTGRES_DB=POSTGRES
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - "9092:9090"
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
  grafana:
    build: './config/grafana'
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
volumes:
  minio_data:
  prometheus_data:



