spring:
  application:
    name: kinopoisk
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
minio:
  url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  login: ${MINIO_LOGIN}
  password: ${MINIO_PASSWORD}